### PR TITLE
Add flake8 bugbear

### PR DESCRIPTION
**Pull request by Mews**
Created this pr in regards to #9 
### Changes
- Added flake8-bugbear to requirements-dev.txt so that it is installed when linting
- Added command in the linting.yml workflow to verify flake8 is picking up flake8-bugbear

## Summary by CodeRabbit

- **Chores**
  - Updated linting workflow to include `flake8-bugbear` verification.
  - Added `flake8-bugbear` to development dependencies.

### CODE REVIEW

**Comment by Seluj78** [comment]
One little tip for your next PR that might come in handy:

https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests

**Review by Seluj78 — APPROVED** [review]

**Comment by Seluj78** [comment]
Congratulations on your first PR on this repository ! 🙌

**Comment by Seluj78** [comment]
And you code is now released here ! 🙌 🔥 https://github.com/Seluj78/flask-utils/releases/tag/v0.4.0

**Comment by Mews** [comment]
Thanks for this opportunity :)
Hopefully this will be the first of many pr's I open on github :P

**Pull request merged**
