### PR TITLE
Add flake8 bugbear

### PR DESCRIPTION
**Pull request by Mews**
Created this pull request in regards to issue #9 
### Changes
- Added flake8-bugbear to requirements-dev.txt so that it is installed when linting
- Added command in the linting.yml workflow to verify flake8 is picking up flake8-bugbear

## Summary by CodeRabbit

- **New Features**
  - Introduced a GitHub Actions workflow for code coverage reporting.
  - Added a Codecov badge to the README for visibility of coverage status.

- **Chores**
  - Updated development dependencies to include `coverage`, `flake8-bugbear`, and `pytest-cov`.
  - Enhanced linting configuration to ensure `flake8-bugbear` is properly utilized.

### CODE REVIEW

**Comment by Seluj78** [comment]
Hi there ! Thank you for the PR @Mews !

On the code side, it looks great to me ! 🙌 

As for the commits, I would like you to adhere to the guideline (you can use `scripts/lint-commits.sh` to check if they match).

Also I prefer to use rebase instead of merge to update branches. Could you do this and then we'll be able to merge your PR 🔥

**Comment by Mews** [comment]
Hi, sorry but this is my first time opening a pr and I'm still learning this git stuff so I'm not entirely sure how to fix those.
Did I understand correctly that the commit messages should follow some sort of format? If so, is there some way to edit the commit messages or how do I proceed?
Also I don't know what you mean by using rebase instead of merge.
Sorry for the trouble

**Comment by Seluj78** [comment]
> Hi, sorry but this is my first time opening a pr and I'm still learning this git stuff so I'm not entirely sure how to fix those. Did I understand correctly that the commit messages should follow some sort of format? If so, is there some way to edit the commit messages or how do I proceed? Also I don't know what you mean by using rebase instead of merge. Sorry for the trouble

Hey no worries, I'm happy to help ! We all had to learn at some point !

So yes that is correct. I personally like my commits to follow a format, which you can find described [here](https://github.com/Seluj78/flask-utils/blob/main/CONTRIBUTING.md#commit-messages). You can also find examples of commit messages following the rules [here](https://github.com/Seluj78/flask-utils/commits/main/)

As for editing a commit, I recommend you search online either how to do an interactive rebase (`git rebase -i`) or use a UI editor which would allow you do to this easily.

Same thing for `merge` vs `rebase`, I advise you search online for what the difference are and how you can rebase your branch onto `main` :)

I am not trying to be rude/lazy by not responding to your questions directly :) The biggest thing you can learn to be a good software engineer is searching yourself ;) Do let me know if you get stuck

**Comment by Mews** [comment]
Update: I think I figured out how to do it from this article https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message#commit-has-not-been-pushed-online

However, doing `git rebase -i HEAD~3` opens some sort of text editor. I am able to replace `pick` with `reword` as per the article's instructions, but then I dont know how to save the file

**Comment by Mews** [comment]
@Seluj78 
Okay I managed to change the commit messages!
Now I just need help with that rebase vs merge thing

**Comment by Seluj78** [comment]
> @Seluj78 Okay I managed to change the commit messages! Now I just need help with that rebase vs merge thing

That's great !

Indeed, you can do an interactive rebase to reword the commits like you did, which is perfect ! And yes, renaming your latest commit is easier since you can simply do `git commit --amend` :)

Now as for rebase vs merge, if you look at https://github.com/Seluj78/flask-utils/pull/22/commits and https://github.com/Seluj78/flask-utils/pull/22/files you can see that you have `merged` into this branch extra stuff that is not needed. A merge will add the changes on top of what you've made, whereas a rebase will place your new changes on top, which is what we want to have a nice history.

What you need to do it checkout your `main` branch, update it from my remote (search on google how to update forked remote branch), then checkout your branch against, and do a `git rebase main` and it will do it magically. Then all you need to do is `git push --force`. More info can be found here: https://git-scm.com/book/en/v2/Git-Branching-Rebasing

**Comment by Mews** [comment]
I don't think it did what it was supposed to ngl
I did `git checkout main` `git fetch upstream` `git rebase upstream/main` `git checkout add-flake8-bugbear` `git rebase main` and `git push --force`

**Comment by Seluj78** [comment]
Hmm indeed it does seem to have removed your changes. Do you remember what you did to do it again ? What I would advise you to do is:

- Close this PR
- Delete the branch
- Checkout `main`
- run `git log` and compare it to https://github.com/Seluj78/flask-utils/commits/main/ to make sure you have the same thing (same commits)
- If that's the case, then you can create the branch again and do your changes, commit again and reopen the PR !

**Comment by Mews** [comment]
Yeah I'll just make the branch again :P

**Pull request closed without merging**
